FROM python:3.10-slim

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y build-essential

# Copy requirements and install
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app source code
COPY app/api /app

# ✅ Copy models directory
COPY models /app/models

CMD ["python", "app.py"]